version: "3.7"

services:
  rabbitmq:
    image: rabbitmq:latest
    restart: always
    # 如果不需要外网访问，使用"127.0.0.1:6379:6379"来限制
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - TZ=Asia/Shanghai
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    volumes:
      # 目录映射
      - "${RABBITMQ_DIR}/data:/data"
    container_name: "rabbitmq"
