server.name: kibana
server.port: 5602
server.host: "0.0.0.0"
elasticsearch.hosts: [ "http://124.70.84.31:30928" ] # 华为云地址
#elasticsearch.hosts: [ "https://engine-dev.piesat.cn/es" ] # 华为云地址
#elasticsearch.hosts: [ "http://10.1.34.17:31920" ] # 私有云地址
#elasticsearch.hosts: [ "http://10.1.34.17:30920" ] # 私有云地址

xpack.monitoring.ui.container.elasticsearch.enabled: true
elasticsearch.username: "elastic"  # es账号
#elasticsearch.password: "123456"   # es密码
elasticsearch.password: "E1OfAx4Nf55513tU4i40eQbA"   # es密码

i18n.locale: zh-CN # 中文


